### ISSUE TITLE
Comment Model

### ISSUE THREAD

**Issue by KLanger98** [KLanger98/Gobble-Global-Snack-Finder#8]
As a user when I make a comment I want the comment to be saved and associated with my account.

Acceptance Criteria:
- Comment model created and linked to snack_id and user_id
- Save the contents of the comment also

**Comment by samanthasamarua** [comment]
I have updated the comment model to suit criteria above. Just need to be checked

**Comment by samanthasamarua** [comment]
Created comment model and linked to snack_id and user_id.
